packages:
  - packages/*
  - apps/*

allowBuilds:
  esbuild: true

catalog:
  "@changesets/cli": 2.31.0
  tsdown: 0.22.3
  turbo: 2.10.0
  typescript: 6.0.3
  vitepress: 1.6.4
  "@types/node": 24.13.2
